apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sredx-backend
  description: Scoring SRE Backend
  annotations:
    github.com/project-slug: octocampus/scoring-sredx-home
  tags:
    - java
    - data
spec:
  type: service
  lifecycle: experimental
  owner: team-a
